### ISSUE TITLE
İntruments

### ISSUE THREAD

**Issue by ygt353** [soitanen/737-800#19]
Some instruments dissappear when we Locate Aircraft At Air using Location/Locate Aircraft in Air menu

**Comment by soitanen** [comment]
Yes, it's known bug for me. interesting thing is, that if you click into
gray picture you will get working instrument on the screen.

2016-03-12 20:30 GMT+03:00 ygt353 notifications@github.com:

**Comment by abcaster** [comment]
And if you reposition twice you get them back again!

**Comment by ygt353** [comment]
Also we need an AP and LNAV to this plane

**Comment by soitanen** [comment]
We? I have working autopilot and lnav mode.... strange, that you havent
13 Мар 2016 г. 11:15 пользователь "ygt353" notifications@github.com
написал:

**Comment by ygt353** [comment]
Well this issue will stay opened until the problems has a fix.

**Comment by soitanen** [comment]
Fixed missing PFD and EICAS after reposition.
