### ISSUE TITLE
New View

### ISSUE THREAD

**Issue by legoboyvdlp** [soitanen/737-800#36]
https://github.com/FGMEMBERS/737-800/commit/d565a08a956781f3f4a70db4f0a84327c4d1fc55
Has a new viewpoint for the left wing.
I don't know how to make a pull request so that only that commit goes in.
@soitanen

**Comment by abcaster** [comment]
Could vi have a center view (and or copilot view) also?

**Comment by legoboyvdlp** [comment]
Well, I'll try! I also need to fix a bug in my viewpoint first.

**Comment by legoboyvdlp** [comment]
@soitanen @abcaster, bugs fixed.

**Comment by abcaster** [comment]
Testing right now, your soundset is pretty noisy!
And would you consider changing the view order to Left Wing->CDU->Cockpit?
I tend to watch the CDU more than I use the passenger(s) view(s) :)
/alex

**Comment by legoboyvdlp** [comment]
@abcaster, go ahead, busy with an essay.

**Comment by YV3399** [comment]
add corrected left and right views copilot left and right wing engine among other and I made other very important improvements and fix :)

**Comment by legoboyvdlp** [comment]
@soitanen see my pull request...
